"""add_receipt_items_table_and_relationship

Revision ID: 3891bc0d0b54
Revises: e47ecdff958f
Create Date: 2026-08-02 11:41:06.636801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3891bc0d0b54'
down_revision: Union[str, Sequence[str], None] = 'e47ecdff958f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_items_id'), 'receipt_items', ['id'], unique=False)
    op.alter_column('receipts', 'merchant_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('receipts', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('receipts', 'receipt_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts', 'receipt_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('receipts', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('receipts', 'merchant_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_receipt_items_id'), table_name='receipt_items')
    op.drop_table('receipt_items')
    # ### end Alembic commands ###
